baseURL = "https://shaninalex.netlify.app"
languageCode = "en-us"
title = "Shanin Blog"

# git submodule add https://github.com/zeon-studio/hugoplate.git themes/hugoplate
theme = "PaperMod"

[taxonomies]
category = 'categories'
tag = 'tags'



# main menu
[[menu.main]]
identifier = "about"
name = "About me"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 40

[params]
ShowShareButtons = true
ShareButtons = ["linkedin", "twitter", "facebook"]

[params.homeInfoParams]
Title = "Hi there!"
Content = "Welcome to my blog. This is not yeat another tech-blog. It's my notes and conspects about things I learned recently or how I did something on my job."

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/funny_droid"

[[params.socialIcons]]
name = "github"
url = "https://github.com/shaninalex"

