baseURL = "http://example.org/"
languageCode = "en-us"
title = "Shanin Blog"

# git submodule add https://github.com/zeon-studio/hugoplate.git themes/hugoplate
theme = "PaperMod"

[taxonomies]
category = 'categories'
tag = 'tags'



[[menu.main]]
identifier = "about"
name = "About me"
url = "/about/"
weight = 10

# [[menu.main]]
# identifier = "tags"
# name = "tags"
# url = "/tags/"
# weight = 20

